### ISSUE TITLE
Remove Up function and use a default export

### ISSUE THREAD

**Issue by pmbanugo** [foobaragency/cf-migrations#55]
For the migration script, we export an `up` function. Since we don't use and need a down function, why don't we just use a default export? 

See an `up` function, I would expect to see a `down` function as in Ruby or some other schema migrations. I think since we don't use/need `down()`, we can just use a default export.

What do you think?

**Comment by n4bb12** [comment]
Actually, we are not exporting an up function. Note that we are doing `export = up` not `export const up =`.

**Comment by pmbanugo** [comment]
Ok. I just noticed some places like in `0047-(productSliderSmall)-add-dedicated-product-select.ts` that had that.
